# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/
ghc-options:
  "$locals": -fwrite-ide-info

resolver: lts-22.20

packages:
- .

extra-deps:
- elm-syntax-0.3.3.0
- git: https://github.com/haskell-to-elm/haskell-to-elm.git
  commit: 962a2e6c90ac5a612de96bf8dfbc2aac090dd116 # "Remove Travis badge"
